apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-sandbox
  namespace: autotest
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: agent-sandbox
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: agent-sandbox
        service: agent-sandbox
    spec:
      containers:
        - env: []
          image: asia-south1-docker.pkg.dev/op-apxor-dev/services/agent:latest
          imagePullPolicy: Always

          name: autotest
          ports:
            - containerPort: 5656
              name: http

          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 200Mi

          volumeMounts:
            - mountPath: /local-agent/configurations
              name: agent-sandbox-go-config
      serviceAccountName: agent-sandbox
      shareProcessNamespace: true
      tolerations:
        - effect: NoSchedule
          key: instance_type
          operator: Equal
          value: spot
      volumes:
        - configMap:
            name: agent-sandbox-go-config
          name: agent-sandbox-go-config
